syntax = "proto3";

package ai.sigmafinancial.aima.v1.generative.services;

import "dtp-aima-gw-protocols-shared/proto/v1/common.proto";

service Generative {
    rpc GetReportCreditEstimate (GetReportCreditEstimateRequest) returns (GetReportCreditEstimateResponse);
    rpc ScheduleReportRaw (ScheduleReportGenerationRequest) returns (common.Empty);
    rpc ScheduleWorkflowRun (ScheduleReportGenerationRequest) returns (common.Empty);
    // Get workflow metadata.
    rpc ViewWorkflow (ViewWorkflowRequest) returns (ViewWorkflowResponse);
    rpc InvokeWorkflow (WorkflowRequest) returns (common.ReportResponse);
    rpc InvokeWorkflowStreaming (WorkflowRequest) returns (stream StreamingWorkflowResponse);
    rpc Chat (ChatRequest) returns (ChatResponse);
    rpc ChatStreaming (ChatRequest) returns (stream StreamingChatResponse);
}

// Estimate the cost of generating a specific report
message GetReportCreditEstimateRequest {
    // Report configuration
    string report_configuration = 1;
}

message GetReportCreditEstimateResponse {
    // The estimated cost of generating the report
    int32 credit_cost = 1;
}

// Schedule the generation of a report
message ScheduleReportGenerationRequest {
    // Report configuration
    string report_configuration = 1;
}

message ScheduleWorkflowRequest {
    string workflow_id = 1;
    map<string, string> parameters = 5;
    // Add additional parameters required to schedule
}

message WorkflowRequest {
    string workflow_id = 1;
    map<string, string> parameters = 5;
}

// Request for getting workflow metadata
message ViewWorkflowRequest {
    // The ID of the workflow being interrogated.
    // 
    // Leave empty to view all workflows associated with account.
    string workflow_id = 1;
}

// Response for getting workflow metadata
message ViewWorkflowResponse {
    repeated Workflow workflows = 1;
}

// The metadata associated with a given workflow.
message Workflow {
    // The workflow's ID.
    string id = 1;
    // The workflow's human-readable name.
    string name = 2;
    // The parameters that can/should be passed to the workflow.
    repeated WorkflowParameter parameters = 3;
}

// A parameter to be passed to a workflow.
message WorkflowParameter {
    // The name of the parameter.
    string name = 1;
    // The type of the parameter.
    WorkflowParameterType type = 2;
    // The parameter's default value (parsed into a string).
    //
    // If the parameter has no default value - and so is non-optional - then
    // this will be an empty string.
    string default_value = 3;
    // An example value for the parameter (parsed into a string).
    //
    // If the parameter has no example value then this will be an empty string.
    string example_value = 4;
    // Allowed values for this parameter (parsed into strings).
    //
    // If the parameter has no allowed values - i.e. it's unconstrained - then
    // this will be an empty list.
    repeated string allowed_values = 5;
    // Determines if the parameter takes a Vector or Array of primitive types
    bool is_array = 6;
}

// Possible types for a workflow parameter.
enum WorkflowParameterType {
	reserved 4;
    WORKFLOW_PARAMETER_TYPE_BOOLEAN = 0;
    WORKFLOW_PARAMETER_TYPE_INTEGER = 1;
    WORKFLOW_PARAMETER_TYPE_FLOAT = 2;
    WORKFLOW_PARAMETER_TYPE_STRING = 3;
    WORKFLOW_PARAMETER_TYPE_OBJECT = 5;
}

message StreamingWorkflowResponse {
    string buffer = 1;
    bool final = 5;
}

message ChatRequest {
    string chat_workflow = 1;
    repeated ChatMessage message = 10;
    map<string, string> parameters = 15;
}

message ChatMessage {
    ChatRole role = 1;
    string content = 2;
}

enum ChatRole {
    CHAT_ROLE_USER = 0;
    CHAT_ROLE_ASSISTANT = 1;
}

message ChatResponse {
    string answer = 1;
}

message StreamingChatResponse {
    string buffer = 1;
    bool final = 5;
}
