syntax = "proto3";

package ai.sigmafinancial.aima.v2.generative.services;

import "dtp-aima-gw-protocols-shared/proto/v1/common.proto";

service Generative {
    rpc InvokeWorkflow (WorkflowRequest) returns (v1.common.ReportResponse);
    rpc InvokeWorkflowStreaming (WorkflowRequest) returns (stream StreamingWorkflowResponse);
}

message WorkflowRequest {
    string workflow_id = 1;
    map<string, ParameterValue> parameters = 5;
}

message ParameterValue {
    oneof value {
        string string = 2;
        bool boolean = 3;
        int64 integer = 4;
        float float = 5;
        ParameterValueArray array = 6;
    }
}

message ParameterValueArray {
    repeated ParameterValue values = 1;
}

message StreamingWorkflowResponse {
    string buffer = 1;
    bool final = 5;
}