syntax = "proto3";

package ai.sigmafinancial.aima.v2.auth;

message Token {
    // Token payload
    TokenData data = 5;
    // Token signature
    string signature = 10;
    // Base64-encoded `data` for the Authorization: Bearer header
    string encoded_data = 15;
}

message TokenData {
    // The token ID
    string id = 1;
    // The ID of the system that signed the token
    string token_signature_id = 5;
    // The App Key used to create the token
    string derived_from = 10;
    // When the token was issued
    int64 created = 15;
    // When the token expires
    int64 expires = 20;
    // The policies the token's scope resolves to
    repeated string policy_id = 25;
}
