syntax = "proto3";

package ai.sigmafinancial.aima.v1.user;

message NewAccount {
    string name = 5;
    string parent_id = 15;
}

message Account {
    string id = 1;
    string name = 5;
    bool active = 10;
    // Could be a subaccount of another
    string parent_id = 15;
    int64 created = 25;
}

message User {
    // The user ID
    string id = 1;
    // Account the user belongs to
    string account_id = 3;
    // The user's email
    string email = 5;
    // The user's first name
    string first_name = 10;
    // The user's last name
    string last_name = 15;
    // SSO ID
    string sso_id = 20;
    // Date user was created
    int64 created = 25;
}