syntax = "proto3";

package ai.sigmafinancial.aima.v1.user;

// NewAccount and Account are defined in shared/proto/v1/account.proto (same package).

message User {
    // The user ID
    string id = 1;
    // Account the user belongs to
    string account_id = 3;
    // The user's email
    string email = 5;
    // The user's first name
    string first_name = 10;
    // The user's last name
    string last_name = 15;
    // SSO ID
    string sso_id = 20;
    // Date user was created
    int64 created = 25;
}